export const activities = [
  {
    subject: 'et',
    description: 'Construção de um marcador de livros.',
    attachments: ['AAT-1'],
    deliveryDate: '23-03-2020',
    deliveryMethod: 'Enviar fotografia do marcador para elisabeteisabel@aevrsa.com',
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'ev',
    description: 'Efetuar resumo do artigo disponível no website da Fundação Calouste Gulbenkian (link abaixo) sobre a artista Maria Antónia Siza. Devem também realizar um autorretrato com base nos desenhos da referida artista.',
    attachments: ['AAT-2', 'AAT-3'],
    deliveryDate: '23-03-2020',
    deliveryMethod: 'Enviar fotografia para elisabeteisabel@aevrsa.com',
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'ing',
    description: 'Aceder ao site da Leya (link abaixo), inscrever-se na sala do 5º ano com o código "qfszs" e realizar os testes disponíveis.',
    attachments: ['AAT-4'],
    deliveryDate: '23-03-2020',
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'mat',
    description: 'Realizar a ficha de trabalho das páginas 16, 17, 22 e 23 do manual - parte 2.',
    deliveryMethod: 'Início das aulas.',
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'cn',
    description: 'Realizar o relatório da atividade efetuada em sala de aula.',
    attachments: ['AAT-5'],
    deliveryDate: '23-03-2020',
    deliveryMethod: 'Enviar fotografia para cristinabarbosa@aevrsa.com',
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'ef',
    description: 'Consulta ao site oficial da plataforma FiTescola (leitura e familiarização sobre a ferramenta de trabalho).',
    attachments: ['AAT-6', 'AAT-7'],
    dateCreation: '19-03-2020',
    dateChanged: '',
  },
  {
    subject: 'hgp',
    description: 'Responder às perguntas das páginas 92 e 93 e à ficha n.º 8 do caderno de atividades.',
    deliveryMethod: 'Início das aulas.',
    dateCreation: '13-03-2020',
    dateChanged: '',
  },
  {
    subject: 'hgp',
    description: 'Enviar fotografia do astrolábio pedido anteriormente.',
    deliveryDate: '27-03-2020',
    deliveryMethod: 'Enviar fotografia para <a href="mailto: filomenaandrade@aevrsa.com">filomenaandrade@aevrsa.com</a>',
    dateCreation: '23-03-2020',
    dateChanged: '',
  },
  {
    subject: 'por',
    description: 'Realizar uma ficha de leitura com base na leitura autónoma de um livro.',
    attachments: ['AAT-8'],
    deliveryMethod: 'Início das aulas.',
    dateCreation: '23-03-2020',
    dateChanged: '',
  },
  {
    subject: 'ef',
    description: 'Continuação da tarefa da semana anterior, concretamente da consulta ao site oficial da plataforma FiTescola (leitura e familiarização sobre a ferramenta de trabalho).',
    attachments: ['AAT-6', 'AAT-7'],
    dateCreation: '24-03-2020',
    dateChanged: '',
  },
  {
    subject: 'tic',
    description: 'Efetuar a autoavaliação.',
    attachments: ['AAT-9'],
    deliveryDate: '27-03-2020',
    dateCreation: '24-03-2020',
    dateChanged: '',
  },
  {
    subject: 'cd',
    description: 'Efetuar a autoavaliação.',
    attachments: ['AAT-10'],
    deliveryDate: '27-03-2020',
    dateCreation: '24-03-2020',
    dateChanged: '',
  },
  {
    subject: 'em',
    description: 'Efetuar a correção do teste de avaliação, com exeção da parte auditiva.',
    attachments: ['AAT-11'],
    deliveryMethod: '1ª sexta-feira de aulas',
    dateCreation: '25-03-2020',
    dateChanged: '',
  },
];
