export enum EActivityGlossary {
  DESCRIPTION = 'Descrição',
  DELIVERY = 'Entrega',
  DATE = 'Data',
  METHOD = 'Forma',
  REQUEST_DATE = 'Data',
  DELIVERY_DATE = 'Data de Entrega',
  DELIVERY_METHOD = 'Método de Entrega',
  ATTACHMENT = 'Anexo',
  ATTACHMENTS = 'Anexos',
  REGISTRATION = 'Atividade registada a',
  SEE_DETAIL = 'Ver Detalhes',
  LAST_ACTIVITIES_LIST_TITLE = 'Últimas Atividades',
  SEE_ALL_ACTIVITIES = 'Ver todas',
  ACTIVITY_LIST_TITLE = 'Lista de Atividades Propostas',
  SUBJECTS_PLACEHOLDER_SELECT = 'Filtar por Disciplina',
  SUBJECTS_NO_MATCHES_SELECT = 'Disciplina não encontrada',
  ACTIVITY_MANAGEMENT_LIST_TITLE = 'Gestão de Atividades',
}
